baseurl = "https://taosue.github.io"
languageCode = "en-us"
title = "Tao Su"
publishDir = "docs"
theme = "yinyang"
DefaultContentLanguage = "cn"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 1

[params]
mainSections = ["posts"]
headTitle = "Tao Su"
[[params.socials]]
name = "About Me"
link = ""
[[params.socials]]
name = "Github"
link = "https://github.com/taosue"
[[params.socials]]
name = "RSS"
link = "/index.xml"
